apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: success-rate
spec:
  args:
    - name: ingress
  metrics:
    - name: success-rate
      interval: 10s
      successCondition: "len(result) > 0 ? result[0] >= 0.9 : true"
      provider:
        prometheus:
          address: http://arms-prom-server:9090
          query: |
            sum(
              rate(nginx_ingress_controller_requests{ingress="{{args.ingress}}",status=~"2.*",service=~"rollouts-demo-stable"}[20s]))
              /
              sum(rate(nginx_ingress_controller_requests{ingress="{{args.ingress}}"}[20s])
            )