apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: success-rate
spec:
  args:
  - name: namespace
    value: default
  - name: service-name
    value: rollouts-demo-stable
  - name: rollouts-pod-template-hash
    valueFrom:
      podTemplateHashValue: Latest
  metrics:
  - name: success-rate
    interval: 10s
    successCondition: result[0] >= 0.95
    provider:
      prometheus:
        address: http://arms-prom-server:9090
        query: |
            sum(
              rate(nginx_ingress_controller_requests{status=~"2.*",service=~"{{args.service-name}}"}[20s]))
              /
              sum(rate(nginx_ingress_controller_requests{service="{{args.service-name}}"}[20s])
            )